FROM python:3.13-slim

ENV POETRY_VERSION=1.5.0
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
RUN curl -sSL https://install.python-poetry.org | python -

ENV PATH="/root/.local/bin:$PATH"
WORKDIR /app

# Copy the dependency files and install packages
COPY pyproject.toml poetry.lock* /app/
RUN poetry config virtualenvs.create false \
    && poetry install --no-dev --no-interaction --no-ansi

# Copy your code
COPY . .

# Set the entrypoint to run your main script using Fire
ENTRYPOINT ["poetry", "run", "python", "main_gcp.py"]
